---
# tasks file for extra-disk-win

- name: create the partition
  win_partition:
    drive_letter: "{{ extra_disk_win_drive_letter }}"
    partition_size: -1
    partition_number: "{{ extra_disk_win_disk_id }}"
    disk_number: "{{ extra_disk_win_disk_id }}"
    state: present

- name: format the volume
  win_format:
    drive_letter: "{{ extra_disk_win_drive_letter }}"
    file_system: "{{ extra_disk_win_fs_format }}"
    new_label: "{{ extra_disk_win_drive_name }}"