---
# tasks file for extra-disk-win

# https://github.com/PowerShell/StorageDsc/wiki#getting-started
- name: install StorageDsc module
  win_psmodule:
    name: StorageDsc
    repository: PSGallery
    state: present
# Verify install: Get-DscResource -Module StorageDsc

- name: copy the disk setup script
  win_template:
    src: templates/setup_secondary_disk.ps1
    dest: C:\setup_secondary_disk.ps1

- name: create the dsc configuration
  win_shell: C:\setup_secondary_disk.ps1

- name: apply the configuration
  win_shell: Start-DscConfiguration -Path C:\setup_secondary_disk -Verbose -Wait

- name: remove the disk setup script
  win_file:
    path: C:\setup_secondary_disk.ps1
    state: absent

- name: remove the configuration directory
  win_file:
    path: C:\setup_secondary_disk
    state: absent

#- name: initialize the disk
#  win_initialize_disk:
#    disk_number: "{{ extra_disk_win_disk_id }}"
#    force: no
#    online: yes
#    style: gpt
#
#- name: create the partition
#  win_partition:
#    drive_letter: "{{ extra_disk_win_drive_letter }}"
#    partition_size: -1
#    partition_number: "{{ extra_disk_win_disk_id }}"
#    disk_number: "{{ extra_disk_win_disk_id }}"
#    state: present
#
#- name: format the volume
#  win_format:
#    drive_letter: "{{ extra_disk_win_drive_letter }}"
#    file_system: "{{ extra_disk_win_fs_format }}"
#    new_label: "{{ extra_disk_win_drive_name }}"